### ISSUE TITLE
Cannot create CognitivePedestrian2D and HeterogeneousPedestrian2D if Alchemist is executed via jar

### ISSUE THREAD

**Issue by Placu95** [AlchemistSimulator/Alchemist#459] opened 2020-06-26 12:10 UTC
#### Environment
OS: Windows 10
Java: 11.0.2 (OpenJDK)
Alchemist: 9.3.0 and later until commit 9e92d2c

### What happens
Launching a simple simulation via the jar file, with the following command:

`java -jar alchemist-redist-9.3.0.jar -y configuration.yml`

will fail with the following exception (short version):

```
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalArgumentException: Cannot create it.unibo.alchemist.model.implementations.nodes.CognitivePedestrian2D with arguments [child:String, male:String]
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:188)
	at it.unibo.alchemist.Alchemist.main(Alchemist.java:143)
Caused by: java.lang.IllegalArgumentException: Cannot create it.unibo.alchemist.model.implementations.nodes.CognitivePedestrian2D with arguments [child:String, male:String]
	at org.danilopianini.jirf.FactoryImpl.lambda$null$6(FactoryImpl.java:57)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.danilopianini.jirf.FactoryImpl.lambda$build$7(FactoryImpl.java:51)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.danilopianini.jirf.FactoryImpl.build(FactoryImpl.java:34)
	at it.unibo.alchemist.loader.YamlLoader$Builder.lambda$new$2(YamlLoader.java:811)
	at it.unibo.alchemist.loader.YamlLoader$BuilderConfiguration.lambda$build$0(YamlLoader.java:864)
	at it.unibo.alchemist.loader.YamlLoader$BuilderConfiguration.ifMap(YamlLoader.java:872)
	at it.unibo.alchemist.loader.YamlLoader$BuilderConfiguration.build(YamlLoader.java:850)
	at it.unibo.alchemist.loader.YamlLoader$Builder.build(YamlLoader.java:830)
	at it.unibo.alchemist.loader.YamlLoader.getWith(YamlLoader.java:555)
	at it.unibo.alchemist.AlchemistRunner.lambda$prepareSimulations$11(AlchemistRunner.java:295)
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:181)
	... 1 more
```

The complete stacktrace is in the file [log.txt](https://github.com/AlchemistSimulator/Alchemist/files/4836747/log.txt)

The simulation file used is here [configuration.yml.txt](https://github.com/AlchemistSimulator/Alchemist/files/4836752/configuration.yml.txt) (there is the final extension `.txt` because Github doesn't allow YAML extension).

The same happens also with `HeterogeneousPedestrian2D`.

**Comment by DanySK** [comment] 2020-06-26 12:46
@paagamelo any hint?

**Comment by paagamelo** [comment] 2020-06-26 13:36
This is the kind of error you get when you forget to put `@JvmOverloads` to a constructor with default parameters in Kotlin. It's strange because pedestrians' loading is tested.

Looking at the stack trace, it seems to me that the simulator is unable to use pedestrians' secondary constructors for some reason. It says:
```
Couldn't convert child from java.lang.String to it.unibo.alchemist.model.cognitiveagents.characteristics.individual.Age
```
Whilst there's a secondary constructor taking in a `String` instead of an `Age`.

@Placu95 Did you check that the issue was present in the commit previous to https://github.com/AlchemistSimulator/Alchemist/commit/9e92d2cdc85f1a20a85c71d9cb32992eff4e2d86? I can't see how upgrading spotbugs could solve it.

**Comment by DanySK** [comment] 2020-06-26 13:45
@Placu95 this bug smells. Why do you say that Github doesn't allow YAML? That's blatantly false, we got a ton of .yml files around.

**Comment by DanySK** [comment] 2020-06-26 13:48
@paagamelo well I'd have some problems converting `"child"` or `"male"` to an Age as well. @Placu95 is that exception **full**? I need to see all the Exceptions suppressed by JIRF

**Comment by Placu95** [comment] 2020-06-26 13:58
@paagamelo I tried with Alchemist at version 9.3.0, commits 9e92d2c and 1f70c89. The bug is present in all three versions.

@DanySK Github doesn't allow to attach YAML file in issue. 

The file log.txt contains the complete stacktrace printed by the simulator.

I can add that if you run Alchemist via Gradle downloading it from maven, all work fine. (I tested this only with Alchemist v9.3.0)

**Comment by DanySK** [comment] 2020-06-26 14:08
@paagamelo can we add the source to the test suite and verify that the bug is reproducibile?

This constructor `it.unibo.alchemist.model.implementations.nodes.CognitivePedestrian2D(it.unibo.alchemist.model.interfaces.environments.EuclideanPhysics2DEnvironment,org.apache.commons.math3.random.RandomGenerator,it.unibo.alchemist.model.cognitiveagents.characteristics.individual.Age,it.unibo.alchemist.model.cognitiveagents.characteristics.individual.Gender)` fails as expected
 
Then this one: `Suppressed: org.danilopianini.jirf.InstancingImpossibleException: Could not create an instance with public it.unibo.alchemist.model.implementations.nodes.CognitivePedestrian2D(it.unibo.alchemist.model.interfaces.environments.EuclideanPhysics2DEnvironment,org.apache.commons.math3.random.RandomGenerator,int,java.lang.String)` also "fails correctly".

The system then tries `it.unibo.alchemist.model.implementations.nodes.CognitivePedestrian2D(it.unibo.alchemist.model.interfaces.environments.EuclideanPhysics2DEnvironment,org.apache.commons.math3.random.RandomGenerator,java.lang.String,java.lang.String)`, and this **should work**, but **fails**

```
Caused by: java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
```

This is the problem

**Comment by DanySK** [comment] 2020-06-26 14:11
@Placu95 how do you get the jar? And: is this class included (use jar -tf)
https://github.com/JetBrains/kotlin/blob/master/core/descriptors/src/org/jetbrains/kotlin/builtins/BuiltInsLoader.kt

**Comment by DanySK** [comment] 2020-06-26 14:13
And also kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl

We maybe are stripping kotlin-reflect from the jar file. But it's very very strange

**Comment by DanySK** [comment] 2020-06-26 14:14
@Placu95 also please try to use the jar you're currently using + the kotlin.reflect 1.3.71 jar and launch the application with

`java -cp alchemist-full.jar kotlin.reflect-1.3.71.jar it.unibo.alchemist.Alchemist <options>`

**Comment by Placu95** [comment] 2020-06-26 14:21
@DanySK the jar contains the two classes.
I downloaded the jar here: https://github.com/AlchemistSimulator/Alchemist/releases/tag/9.3.0

**Comment by Placu95** [comment] 2020-06-26 14:25
@DanySK I tried also `java -cp alchemist-full.jar kotlin.reflect-1.3.71.jar it.unibo.alchemist.Alchemist <options>` and the bug is still present

**Comment by DanySK** [comment] 2020-06-26 14:26
No do **not** use Alchemist 9.3.0. Use the latest development version.

**Comment by DanySK** [comment] 2020-06-26 14:27
9.3.0 is no longer supported, unless the bug also affects the current development version. We need to release 10.0.0 asap

**Comment by paagamelo** [comment] 2020-06-26 14:29
@Placu95 Ah sorry, I thought the bug disappeared in commit https://github.com/AlchemistSimulator/Alchemist/commit/9e92d2cdc85f1a20a85c71d9cb32992eff4e2d86.

> @paagamelo can we add the source to the test suite and verify that the bug is reproducibile?

@DanySK We already test pedestrians' loading using that constructor, and everything works via Gradle. Or you meant adding a test launching the full jar?

**Comment by Placu95** [comment] 2020-06-26 14:33
@DanySK also `alchemist-full-9.3.0-devyg+9e92d2cdc-all.jar` contains the two classes.
I obtained the jar via the gradle task shadowJar.

`java -cp "alchemist-full-9.3.0-devyg+9e92d2cdc-all.jar";kotlin.reflect-1.3.71.jar it.unibo.alchemist.Alchemist -y configuration.yml` doesn't work.

**Comment by DanySK** [comment] 2020-06-26 14:36
Can you list the content of the `META-INF/services` folder in that jar?

**Comment by Placu95** [comment] 2020-06-26 14:44
the directory `META-INF` contains only the file `MANIFEST.MF`

**Comment by DanySK** [comment] 2020-06-26 14:51
what-the-fuck.
The file is in kotlin-reflect, and we need to pack it, so I'll change that. But it should work with the other command.
What is the content of `META-INF/services` in the kotlin-reflect jar you are using?

And is the command accurate? If so, you mistaken the reflect jar name (dash, not dot). Use the autocompletion!

**Comment by Placu95** [comment] 2020-06-26 15:08
Ok. I tried this `java -cp "alchemist-full-9.3.0-devyg+9e92d2cdc-all.jar";kotlin-reflect-1.3.71.jar it.unibo.alchemist.Alchemist -y configuration.yml` (with dash) and it works

**Comment by DanySK** [comment] 2020-06-26 15:09
YEAH!!!!
Then solution's easy... let me implement it

**Comment by DanySK** [comment] 2020-06-26 15:33
try with fc6172a9951913a8831b0e905051166379b783ec and let me know @Placu95

**Comment by Placu95** [comment] 2020-06-26 15:46
It works

**Comment by DanySK** [comment] 2020-06-26 15:48
Closing

**Closed by DanySK** 2020-06-26 15:48 UTC
